Repository rcpch/rcpch-audit-engine, pull requests merged in 2023-11, with the labels that each got.

#617 Eatyourpeas/issue609
  .github/workflows/run-docker-compose-test-on-pr.yml
  .github/workflows/run-tests-on-pr.yml
  .gitignore
  docker-compose.yml
  envs/env-template
  epilepsy12/admin.py
  epilepsy12/common_view_functions/__init__.py
  epilepsy12/common_view_functions/aggregate_by.py
  epilepsy12/common_view_functions/sanction_user_access.py
  epilepsy12/general_functions/construct_confirm_email.py
  epilepsy12/general_functions/construct_transfer_email.py
  epilepsy12/migrations/0012_alter_countrykpiaggregation_options_and_more.py
  epilepsy12/migrations/0013_alter_nationalkpiaggregation_cohort.py
  epilepsy12/migrations/0014_historicalsite_active_transfer_and_more.py
  epilepsy12/migrations/0015_historicalsite_transfer_origin_organisation_and_more.py
  epilepsy12/models_folder/epilepsy12_site.py
  epilepsy12/models_folder/kpi_aggregation.py
  epilepsy12/tasks.py
  epilepsy12/urls.py
  epilepsy12/views/case_views.py
  epilepsy12/views/organisation_views.py
  epilepsy12/views/registration_views.py
  epilepsy12/views/user_management_views.py
  rcpch-audit-engine/celery.py
  rcpch-audit-engine/settings.py
  static/styles/nav.css
  static/styles/style.css
  templates/base.html
  templates/epilepsy12/error_pages/rcpch_403.html
  templates/epilepsy12/nav.html
  templates/epilepsy12/open_access.html
  templates/epilepsy12/partials/case_table.html
  templates/epilepsy12/partials/kpis/kpis.html
  templates/epilepsy12/partials/page_elements/rcpch_organisations_select.html
  templates/epilepsy12/partials/selected_organisation_summary.html
  templates/registration/password_reset.html
  templates/registration/transfer_epilepsy12_site_email.html
  templates/registration/transfer_epilepsy12_site_response.html
  templates/two_factor/profile/profile.html
Labels: before-launch

#622 UI improvements
  epilepsy12/views/case_views.py
  epilepsy12/views/user_management_views.py
  static/styles/footer.css
  static/styles/style.css
  templates/base.html
  templates/epilepsy12/cases/cases.html
  templates/epilepsy12/epilepsy12index.html
  templates/epilepsy12/footer.html
  templates/epilepsy12/nav.html
  templates/epilepsy12/partials/page_elements/rcpch_multiple_toggle.html
  templates/epilepsy12/partials/selected_organisation_summary.html
  templates/registration/user_management/epilepsy12_user_list.html
Labels: before-launch, user-interface

#626 Issue624Login
  documentation/docs/development/manual-setup.md
  epilepsy12/forms_folder/epilepsy12_user_form.py
  epilepsy12/migrations/0009_seed_comorbidities.py
  epilepsy12/migrations/0016_alter_epilepsy12user_role_and_more.py
  epilepsy12/models_folder/epilepsy12user.py
  epilepsy12/tests/view_tests/authentication_and_authorization/test_login.py
Labels: bug, before-launch

#627 transfer documentation
  documentation/docs/clinician-users/entering-patient-data.md
  documentation/docs/clinician-users/user-group-permissions.md
  epilepsy12/migrations/0016_alter_site_transfer_origin_organisation.py
  epilepsy12/models_folder/epilepsy12_site.py
Labels: bug, documentation, before-launch

#651 Cohort-data
  epilepsy12/common_view_functions/aggregate_by.py
  epilepsy12/common_view_functions/calculate_kpi_functions/score_kpi_3.py
  epilepsy12/common_view_functions/recalculate_form_generate_response.py
  epilepsy12/common_view_functions/validate_form_update_model.py
  epilepsy12/coverage_tests/registration_tests.py
  epilepsy12/general_functions/cohort_number.py
  epilepsy12/management/commands/create_e12_records.py
  epilepsy12/management/commands/seed.py
  epilepsy12/migrations/0019_historicalregistration_completed_first_year_of_care_date_and_more.py
  epilepsy12/migrations/0020_remove_historicalregistration_registration_close_date_and_more.py
  epilepsy12/models_folder/registration.py
  epilepsy12/tasks.py
  epilepsy12/tests/common_view_functions_tests/calculate_kpi_tests/test_measure_3.py
  epilepsy12/tests/general_functions_tests/test_cohort_calculations.py
  epilepsy12/tests/model_tests/test_registration.py
  epilepsy12/views/organisation_views.py
  epilepsy12/views/registration_views.py
  templates/epilepsy12/partials/registration/registration_dates.html
Labels: bug, before-launch, refactor
