Repository rcpch/rcpch-audit-engine, pull requests merged in 2023-03, with the labels that each got.

#270 Overhauled the footer styling
  static/styles/footer.css
  static/styles/style.css
  templates/epilepsy12/footer.html
Labels: user-interface

#275 Mental Health support KPI
  epilepsy12/common_view_functions/calculate_kpis.py
Labels: bug

#280 Scores negative if mental health support sought but not found and no help needed or in place
  epilepsy12/common_view_functions/calculate_kpis.py
  epilepsy12/models_folder/kpi.py
Labels: bug, for-mvp

#281 implement 5000 character cut off
  epilepsy12/models_folder/episode.py
  epilepsy12/templatetags/epilepsy12_template_tags.py
  epilepsy12/view_folder/multiaxial_diagnosis_views.py
  templates/epilepsy12/partials/multiaxial_diagnosis/description.html
Labels: bug, user-interface

#282 Redirect on create case
  epilepsy12/view_folder/case_views.py
Labels: for-mvp, user-interface

#293 Eatyourpeas/issue287
  docker-compose.dev-init.yml
  epilepsy12/common_view_functions/__init__.py
  epilepsy12/common_view_functions/aggregate_by.py
  epilepsy12/common_view_functions/calculate_kpis.py
  epilepsy12/common_view_functions/report_queries.py
  epilepsy12/general_functions/cohort_number.py
  epilepsy12/migrations/0058_alter_episode_description_and_more.py
  epilepsy12/templatetags/epilepsy12_template_tags.py
  epilepsy12/view_folder/hospital_views.py
  static/styles/style.css
  templates/epilepsy12/partials/kpis/kpi.html
  templates/epilepsy12/partials/kpis/kpis.html
Labels: for-mvp

#306 Cannot enter dates by typing
  epilepsy12/forms_folder/epilepsy12_user_form.py
  epilepsy12/models_folder/epilepsy12user.py
  epilepsy12/views.py
  templates/epilepsy12/partials/assessment/consultant_paediatrician.html
  templates/epilepsy12/partials/assessment/epilepsy_nurse.html
  templates/epilepsy12/partials/assessment/epilepsy_surgery.html
  templates/epilepsy12/partials/assessment/paediatric_neurology.html
  templates/epilepsy12/partials/investigations/eeg_information.html
  templates/epilepsy12/partials/investigations/mri_brain_information.html
  templates/epilepsy12/partials/management/antiepilepsy_medicines/antiepilepsy_medicine.html
  templates/epilepsy12/partials/management/individualised_care_plan.html
  templates/epilepsy12/partials/multiaxial_diagnosis/comorbidities/comorbidity.html
  templates/epilepsy12/partials/multiaxial_diagnosis/episode.html
  templates/epilepsy12/partials/multiaxial_diagnosis/syndrome.html
  templates/epilepsy12/partials/registration/registration_dates.html
Labels: feature request, user-interface

#313 Eatyourpeas/issue312
  epilepsy12/view_folder/hospital_views.py
  templates/epilepsy12/partials/kpis/kpis.html
Labels: for-mvp, user-interface

#355 New account link expired
  epilepsy12/forms_folder/epilepsy12_user_form.py
  epilepsy12/view_folder/user_management_views.py
  templates/registration/admin_create_user.html
Labels: bug
