Repository rcpch/rcpch-audit-engine, pull requests merged in 2024-01, with the labels that each got.

#726 Eatyourpeas/issue538
  epilepsy12/views/assessment_views.py
  epilepsy12/views/case_views.py
  epilepsy12/views/registration_views.py
  epilepsy12/views/user_management_views.py
  templates/epilepsy12/forms/case_form.html
  templates/epilepsy12/partials/case_table.html
Labels: bug, user-interface, priority: high

#759 fix FPA min date for users
  epilepsy12/views/registration_views.py
Labels: bug, priority: highest

#758 Extend timeout in debug mode to reduce re logging in
  .github/workflows/run-docker-compose-test-on-pr.yml
  README.md
  envs/env-template
  rcpch-audit-engine/git_context_processor.py
  rcpch-audit-engine/settings.py
Labels: refactor

#771 Issue769 - UI confusion around deleting a user
  static/styles/buttons.css
  static/styles/progress-bars.css
  templates/epilepsy12/forms/case_form.html
  templates/epilepsy12/partials/case_table.html
Labels: feature request

#775 date change event makes ajax call too soon
  static/hyperscript_0.9.12/hyperscript.min.js
  templates/base.html
  templates/epilepsy12/partials/page_elements/date_field.html
Labels: bug, priority: medium

#776 case pagination not working if filter applied
  epilepsy12/templatetags/epilepsy12_template_tags.py
  epilepsy12/views/case_views.py
  templates/epilepsy12/cases/cases.html
  templates/epilepsy12/partials/case_table.html
Labels: bug, priority: medium
