Repository rcpch/rcpch-audit-engine, pull requests merged in 2024-03, with the labels that each got.

#817 fix back button in otp workflow
  templates/two_factor/core/otp_required.html
Labels: bug

#815 Eatyourpeas/issue813
  epilepsy12/tests/view_tests/permissions_tests/test_permissions_delete.py
  epilepsy12/views/user_management_views.py
  templates/registration/admin_create_user.html
  templates/registration/user_management/epilepsy12_user_table.html
Labels: bug

#819 Eatyourpeas/issue818
  documentation/docs/development/key-performance-indicators.md
  epilepsy12/common_view_functions/calculate_kpi_functions/score_kpi_3.py
  epilepsy12/tests/common_view_functions_tests/calculate_kpi_tests/test_measure_3.py
Labels: feature request, to-close-with-confirmation

#823 Adds-documentation-page-on-environment-variables
  documentation/docs/development/application-structure.md
  documentation/docs/development/environment-variables.md
  documentation/docs/development/manual-setup.md
  documentation/mkdocs.yml
Labels: documentation

#842 Error saving general paediatric centre
  templates/epilepsy12/partials/page_elements/organisations_select.html
Labels: bug

#839 Logout button is broken
  templates/epilepsy12/nav.html
Labels: bug

#827 disable_save_postcode_unknown
  templates/epilepsy12/cases/postcode_options.html
  templates/epilepsy12/cases/unknown_postcode.html
  templates/epilepsy12/forms/case_form.html
Labels: bug

#826 Eatyourpeas/deprivation_update_postcode_unknown
  epilepsy12/models_folder/case.py
  epilepsy12/tests/model_tests/test_case.py
Labels: bug

#849 aggregate-only-cases-that-completed-full-year
  documentation/docs/development/key-performance-indicators.md
  epilepsy12/common_view_functions/__init__.py
  epilepsy12/common_view_functions/aggregate_by.py
  epilepsy12/common_view_functions/calculate_kpi_functions/__init__.py
  epilepsy12/constants/abstraction_levels.py
  epilepsy12/general_functions/fetch_snomed.py
  epilepsy12/management/commands/seed.py
  epilepsy12/models_folder/kpi_aggregation.py
  epilepsy12/models_folder/registration.py
  epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_get_filtered_cases_queryset_for.py
  epilepsy12/views/organisation_views.py
  templates/epilepsy12/partials/organisation/individual_metrics.html
Labels: bug, feature request
